.Dd June 16, 2024
.Dt LIBSOX 3
.Os
.Sh NAME
.Nm libsox
.Nd audio file-format and effect library
.Sh SYNOPSIS
.In sox.h
.Pp
.Ft int
.Fn sox_init "void"
.Ft void
.Fn sox_quit "void"
.Ft sox_format_t *
.Fn sox_open_read "char const * path" "sox_signalinfo_t const * signal" "sox_encodinginfo_t const * encoding" "char const * filetype"
.Ft sox_format_t *
.Fn sox_open_write "char const * path" "sox_signalinfo_t const * signal" "sox_encodinginfo_t const * encoding" "char const * filetype" "sox_oob_t const * oob" "sox_bool (*overwrite)(char const *)"
.Ft size_t
.Fn sox_read "sox_format_t * format" "sox_sample_t * buf" "size_t len"
.Ft size_t
.Fn sox_write "sox_format_t * format" "sox_sample_t const * buf" "size_t len"
.Ft int
.Fn sox_seek "sox_format_t * format" "off_t offset"
.Ft int
.Fn sox_close "sox_format_t * format"
.Ft sox_effect_handler_t const *
.Fn sox_find_effect "char const * name"
.Ft sox_effect_t *
.Fn sox_create_effect "sox_effect_handler_t const * handler"
.Ft int
.Fn sox_effect_options "sox_effect_t * effect" "int argc" "char ** const argv"
.Ft sox_effects_chain_t *
.Fn sox_create_effects_chain "sox_encodinginfo_t const * ienc" "sox_encodinginfo_t const * oenc"
.Ft int
.Fn sox_add_effect "sox_effects_chain_t * chain" "sox_effect_t * effect" "sox_signalinfo_t * in" "sox_signalinfo_t const * out"
.Ft void
.Fn sox_delete_effects_chain "sox_effects_chain_t * chain"
.Sh DESCRIPTION
.Nm
is a library of sound sample file format readers/writers and sound effects.
It is mainly developed to be used by
.Xr sox 1
but any audio application might find it useful.
.Pp
All audio formats and sound effects operate
with an internal sample format of signed 32-bit integer.
This can cause problems;
for example, distortion might occur
when mixing two channels down to mono with the obvious
.Sy *obuf++ = (*ibuf++ + *ibuf++)/2
since the intermediate addition can overflow.
Doing
.Sy *obuf++ = *ibuf++/2 + *ibuf++/2
instead would get around that problem,
at the expense of the least significant bit.
.Pp
.Nm
always stores multichannel data interleaved, i.e.
successive samples in the stream are the samples of respective channels.
For stereo data, this means a sample from the left channel
followed by a sample from the right channel.
Quadraphonic data is stored as
left front, right front, left rear, right rear.
.Pp
The following structures are used to specify
the audio signal properties and the encoding of samples:
.Bd -literal
typedef struct sox_signalinfo_t {
	sox_rate_t	rate;
	unsigned	channels;
	unsigned	precision;
	uint64_t	length;
	double *	mult;
} sox_signalinfo_t;
.Ed
.Bd -literal
typedef struct sox_encodinginfo_t {
	sox_encoding_t	encoding;
	unsigned	bits_per_sample;
	double		compression;
	sox_option_t	reverse_bytes;
	sox_option_t	reverse_nibbles;
	sox_option_t	reverse_bits;
	sox_bool	opposite_endian;
} sox_encodinginfo_t;
.Ed
.Pp
.Fn sox_format_init
performs initialization related to all file format handlers.
This should be called before any other file operations.
.Fn sox_format_quit
performs cleanup related to all file format handlers.
This should be called after all file operations are done.
.Pp
.Fn sox_open_read
opens the named file for reading.
A special name of
.Dq -
can be used to read data from stdin.
If
.Fa signal
is not NULL, it specifies the properties of the audio signal
such as the sample rate or the number of channels.
If
.Fa encoding
is not NULL, it specifies the sample encoding.
Both
.Fa signal
and
.Fa encoding
are normally only needed for headerless audio files.
If
.Fa filetype
is not NULL, it specifies the file type, such as
.Dq wav ;
otherwise, it is guessed from the name extension or the header.
.Pp
.Fn sox_open_write
opens the named file for writing.
A special name of
.Dq -
can be used to write data to stdout.
If
.Fa signal
or
.Fa encoding
are not NULL, they specify the properties of
the audio signal or the encoding of samples;
for writing, this generally needs to be specified,
as most file formats can store data using various
sample rates, sample sizes, encodings, etc.
The structures filled during
.Fn sox_open_read
can be used to write data in the same format that was read.
If
.Fa filetype
is not NULL, it specifies the file type;
otherwise, the file type is guessed from the filename extension.
If
.Fa oob
is not NULL and the file formats supports comments or other out-of-bound data,
these will be stored in the file header.
If
.Fa overwrite
is not NULL and the file already exists,
the function is called, with the file name as an argument,
to determine whether the file can be overwritten.
The default is to overwrite existing files.
.Pp
.Fn sox_read
reads
.Fa len
samples into
.Fa buf
using the format handler specified by
.Fa format .
It is the caller's responsibility to provide a large enough buffer.
Samples are converted to 32-bit signed integers before being placed in
.Fa buf .
The value of
.Fa len
is the number of samples accross all channels;
if it is not divisible by the number of channels,
the behaviour is undefined.
.Pp
.Fn sox_write
writes
.Fa len
samples from
.Fa buf
using the format handler specified by
.Fa format .
The data in
.Fa buf
are treated as 32-bit signed integers
and are converted as specified by the
.Fa format .
The value of
.Fa len
is the number of samples across all channels.
If it is not divisible by the number of channels,
the behaviour is undefined.
.Pp
.Fn sox_seek
positions the file associated with
.Fa format
to the given
.Fa offset .
.Pp
.Fn sox_close
dissociates the given
.Fa format
pointer from its underlying file and set of functions.
If the format handler was being used for output,
any buffered data is written first.
.Pp
.Fn sox_find_effect
finds and effect by the given
.Fa name ,
returning a pointer to its handler.
.Fn sox_create_effect
instantiates an effect given its
.Fa handler .
.Fn sox_effect_options
passes options to the effect to control its behavior.
.\"It will return SOX_EOF if there were any invalid options passed in.
If successful, the
.Fa sox_signalinfo_t
structure stored in
.Fa effect->in_signal
will optionally contain the rate and channel count
the effect expects on input and
.Fa effect->out_signal
will optionally contain the rate and channel count of the output.
When present, this information should be used to make sure
appropriate effects are placed in the effects chain
to handle any needed conversions.
Passing in options is only supported before the effect is ever started.
.Pp
.Fn sox_create_effects_chain
creates an effects chain that effects can be added to;
.Fa ienc
and
.Fa oenc
are the signal encoding of the input and output of the chain.
The memory pointed to by
.Fa ienc
and
.Fa oenc
is stored internally and should not be freed.
It is OK if these encodings change over time to reflect
new input or output encodings as they are referenced only
when effects are started or restarted.
.Pp
.Fn sox_add_effect
adds an
.Fa effect
to an existing effects
.Fa chain .
The
.Fa in
encoding specifies the encoding of the effect's input, while
.Fa out
is a suggestion of how the output should be encoded.
Depending on the effect's options and what
.Fa in
says, the effect may choose a different encoding.
The output sample rate and number of channels the effect produces
are written back to
.Fa in ,
ready for the next effect in the chain to use:
it can be passed to subsequent calls to
.Fn sox_add_effect
so that the changes can be propagated to subsequent effects.
.Pp
.Fn sox_delete_effects_chain
releases any resources reserved during the creation of the
.Fa chain .
This will also delete any effects in the chain.
.Sh RETURN VALUES
.Fn sox_open_read
and
.Fn sox_open_write
return a pointer to a filled
.Ft sox_format_t
structure, which can be passed to the readers and writers.
If an error occurs, NULL is returned.
.Pp
.Fn sox_read
and
.Fn sox_write
return the number of samples successfully read or written.
This can be less than the requested
.Fa len
when short-reading towards the end of the file.
If the end of file is reached, or an error occurs, SOX_EOF is returned.
Note that no distinction is made between end of file and an error.
.Pp
.Fn sox_close
returns
.Dv SOX_SUCCESS
on success and
.Dv SOX_EOF
on error.
In either case, any further access, including another call to
.Fn sox_close ,
will result in undefined behavior.
.Pp
.Fn sox_seek
returns SOX_SUCCESS on success and SOX_EOF on error,
for example if the file is not seekable.
.Pp
.Fn sox_find_effect
returs a pointer to the named effect's handler
if the effect exists, and NULL otherwise.
.\" FIXME move this to a comment in skel*.c
Each effect runs with one input and one output stream.
An effect's implementation comprises six functions that may be called
to the follow flow diagram:
.EX
LOOP (invocations with different parameters)
  getopts
  LOOP (invocations with the same parameters)
    LOOP (channels)
      start
    LOOP (whilst there is input audio to process)
      LOOP (channels)
        flow
    LOOP (whilst there is output audio to generate)
      LOOP (channels)
        drain
    LOOP (channels)
      stop
  kill
.EE
Notes: For some effects, some of the functions may not be needed and can
be NULL.  An effect that is marked `MCHAN' does not use the LOOP
(channels) lines and must therefore perform multiple channel processing
inside the affected functions.  Multiple effect instances may be
processed (according to the above flow diagram) in parallel.
.TP 20
getopts
is called with a character string argument list for the effect.
.TP 20
start
is called with the signal parameters for the input and output
streams.
.TP 20 
flow
is called with input and output data buffers,
and (by reference) the input and output data buffer sizes.
It processes the input buffer into the output buffer,
and sets the size variables to the numbers of samples
actually processed.
It is under no obligation to read from the input buffer or
write to the output buffer during the same call.  If the
call returns SOX_EOF then this should be used as an indication
that this effect will no longer read any data and can be used
to switch to drain mode sooner.
.TP 20 
drain
is called after there are no more input data samples.
If the effect wishes to generate more data samples
it copies the generated data into a given buffer
and returns the number of samples generated.
If it fills the buffer, it will be called again, etc.
The echo effect uses this to fade away.
.TP 20
stop
is called when there are no more input samples and no more output
samples to process.
It is typically used to release or close resources (e.g. allocated
memory or temporary files) that were set-up in
.IR start .
See echo.c for an example.
.TP 20
kill
is called to allow resources allocated by
.I getopts
to be released.
See pad.c for an example.
.Sh SEE ALSO
.Xr sox 1 ,
.Xr soxformat 7
and
.Pa example*.c
files in the source.
.Sh AUTHORS
.An Chris Bagwell Aq Mt cbagwell@users.sourceforge.net
.\"Copyright 1991 Lance Norskog and Sundry Contributors.
.\"Copyright 1998-2011 Chris Bagwell and SoX Contributors.
.\"
.\"This library is free software; you can redistribute it and/or modify
.\"it under the terms of the GNU Lesser General Public License as published by
.\"the Free Software Foundation; either version 2.1, or (at your option)
.\"any later version.
.\"
.\"This library is distributed in the hope that it will be useful,
.\"but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"GNU Lesser General Public License for more details.
.Sh BUGS
This manual page is incomplete.
