.Dd June 10, 2024
.Dt SOXFORMAT 7
.Os
.Sh NAME
.Nm soxformat
.Nd audio formats supported by SoX
.Sh DESCRIPTION
Format types that SoX can determine by a filename extension
are listed by that extension.
Format types that are optionally built into SoX are marked
.Dq optional .
Format types that can (also) be handled by sndfile are listed under
.Dq sndfile .
This might be useful if you have a file that doesn't work
with SoX's default format readers and writers,
but there is an external reader or writer for that format.
.Bl -tag -width xx
.It raw, f32, f64, s8, s16, s24, s32, u8, u16, u24, u32, ul, al, lu, la
Raw (headerless) audio files.
For raw, the sample rate and the data encoding
must be given using command-line options;
for the other listed types,
the sample rate defaults to 8kHz (but may be overridden),
and the data encoding is defined by the given suffix.
Thus f32 and f64 indicate files encoded as
32 and 64-bit floating point PCM, respectively;
s8, s16, s24, and s32 indicate 8, 16, 24,
and 32-bit signed integer PCM, respectively;
u8, u16, u24, and u32 indicate 8, 16, 24,
and 32-bit unsigned integer PCM, respectively;
ul indicates `\(*m-law' (8-bit), al indicates `A-law' (8-bit), and
lu and la are inverse bit order `\(*m-law' and inverse bit order `A-law'.
The number of channels defaults to 1, but may be overridden.
.It 8svx
Amiga 8SVX musical instrument description format.
.It aiff, aif
AIFF files as used on old Apple Macs, Apple IIc/IIgs and SGI.
SoX's AIFF support does not include multiple audio chunks,
or the 8SVX musical instrument description format.
AIFF files are multimedia archives and
can have multiple audio and picture chunks;
you may need a separate tool to work with them.
AIFF has been superseded by CAF.
.It aiffc, aifce
AIFF-C is a format based on AIFF
that was created to allow handling compressed audio.
It can also handle little endian uncompressed linear data
that is often referred to as
.Dq sowt
encoding.
This encoding has also become the defacto format produced
by modern Macs as well as iTunes on any platform.
AIFF-C files produced by other applications
typically have the file extension
.Dq aif
and require looking at its header to detect the true format.
The
.Dq sowt
encoding is the only encoding that SoX can handle with this format.
AIFF-C is defined in DAVIC 1.4 Part 9 Annex B.
This format is referred from ARIB STD-B24,
which is specified for Japanese data broadcasting.
No private chunks are supported.
.It alsa (optional)
Advanced Linux Sound Architecture device driver.
ALSA is only used in Linux-based operating systems,
though these might support OSS (see below) as well.
.It amb
Ambisonic B-Format: a specialisation of WAV
with between 3 and 16 channels of audio
for use with an Ambisonic decoder.
It is up to the user to get the channels together
in the right order and at the correct amplitude.
.It anb (optional)
Adaptive Multi Rate Narrow Band speech codec;
a lossy format used in 3rd generation mobile telephony
and defined in 3GPP TS 26.071 et al.
AMR-NB audio has a fixed sampling rate of 8 kHz
and supports encoding to the following bit-rates,
selected by the
.Fl C
option of
.Xr sox 1 :
.Pp
.Bl -inset -compact
.It 0 = 4.75 kbit/s
.It 1 = 5.15 kbit/s
.It 2 = 5.9 kbit/s
.It 3 = 6.7 kbit/s
.It 4 = 7.4 kbit/s
.It 5 = 7.95 kbit/s
.It 6 = 10.2 kbit/s
.It 7 = 12.2 kbit/s
.El
.It amr, awb (optional)
Adaptive Multi Rate Wide Band speech codec;
a lossy format used in 3rd generation mobile telephony
and defined in 3GPP TS 26.171 et al.
AMR-WB audio has a fixed sampling rate of 16 kHz
and supports encoding to the following bit-rates,
as selected by the
.Fl C
option.
.Pp
.Bl -inset -compact
.It 0 = 6.6 kbit/s
.It 1 = 8.85 kbit/s
.It 2 = 12.65 kbit/s
.It 3 = 14.25 kbit/s
.It 4 = 15.85 kbit/s
.It 5 = 18.25 kbit/s
.It 6 = 19.85 kbit/s
.It 7 = 23.05 kbit/s
.It 8 = 23.85 kbit/s
.El
.It ao (optional)
Xiph.org's Audio Output device driver; works only for playing.
It supports a wide range of devices and sound systems.
.It au, snd
Sun Microsystems AU files.
There are many types of AU files;
DEC has its own with a different magic number
and little-endian byte order.
To write a DEC file, use the
.Fl L
option for the output file.
Some .au files with invalid AU headers,
notably some of the original Sun \(*m-law 8000 Hz files,
can be dealt with using the
.Dq ul
format (see below).
.It avr
Audio Visual Research format;
used by old Apple Macintosh computers.
.It caf (optional)
Apple's Core Audio File format.
.It cdda, cdr
Compact Disc Digital Audio (raw audio).
CDDA has two audio channels formatted as
16-bit signed integers (big endian) at a sample rate of 44100 Hz.
The number of (stereo) samples in each CDDA track is always a multiple of 588.
.It coreaudio (optional)
.\" FIXME Reorder so that audio drivers are separate
MacOS CoreAudio device driver.
If a filename is not specific or if the name is "default"
then the default audio device is selected.
Any other name will be used to select a specific device.
Valid names are listed in the System Preferences under the Sound menu.
For example:
.Bd -literal
sox infile -t coreaudio
sox infile -t coreaudio default
sox infile -t coreaudio "Internal Speakers"
.Ed
.\" FIXME Say this generally for output drivers:
.\" See also
.\".BR play (1),
.\".BR rec (1),
.\"and
.\".BR sox (1)
.\".BR \-d .
.It cvs, cvsd
Continuously Variable Slope Delta modulation.
A headerless format used to compress speech audio.
This format is sometimes used with bit-reversed samples; the
.Fl X
format option can be used to set the bit-order.
.It cvu
Continuously Variable Slope Delta modulation (unfiltered).
This is an alternative handler for CVSD that is unfiltered
but can be used with any bit-rate.
.It dat
Text Data files.
These files contain a textual representation of the sample data.
First line specifies the sample rate,
second line specifies the number of channels.
Subsequent lines contain two or more numeric data items:
the time since the beginning of the first sample
and the sample value for each channel.
Values are normalized to [-1,1].
This file format can be used to create data files
for external programs such as FFT analysers or graph routines.
.It dvms, vms
Used in Germany to compress speech audio for voice mail.
A self-describing variant of the cvsd format.
.It fap
See paf.
.It flac (optional)
Free Lossless Audio CODEC compressed audio.
FLAC is an open, patent-free codec designed for compressing music.
SoX can read native FLAC files (.flac) but not Ogg FLAC files (.ogg);
see
.Dq ogg
below for Ogg Vorbis support.
SoX can write native FLAC files
according to a given or default compression level:
the default compression level of 8 gives the best (but slowest) compression;
a level of 0 gives the least (but fastest) compression.
The compression level is selected using the
.Fl C
option.
.It gsrt
Grandstream ring-tone files.
Whilst this file format can contain A-Law, \(*m-law,
GSM, G.722, G.723, G.726, G.728, or iLBC encoded audio,
SoX only supports reading and writing A-Law and \(*m-law.
.It gsm (optional)
GSM 06.10 Lossy Speech Compression.
A lossy format for compressing speech which is used
in the Global Standard for Mobile telecommunications (GSM).
It's good for its purpose, shrinking audio data size,
but it will introduce lots of noise when a given audio signal
is encoded and decoded multiple times.
.It hcom
Macintosh HCOM files: Mac FSSD files with Huffman compression.
.It htk
Single channel 16-bit PCM format used by HTK,
a toolkit for building Hidden Markov Model speech processing tools.
.It ima
A headerless file of IMA ADPCM audio data.
.It lpc (optional)
LPC-10 is a compression scheme for speech.
There is no associated file format, so SoX's implementation is headerless.
.It mat, mat4, mat5 (optional)
Matlab 4.2/5.0 format; mat is the same as mat4.
.It maud
An IFF-conforming audio file type
published along with the `Toccata' sound-card on the Amiga.
Allows 8bit linear, 16bit linear, A-Law, \(*m-law in mono and stereo.
.It mp3, mp2 (optional)
MP3 compressed audio;
MP3 (MPEG Layer 3) is a part of
the MPEG standards for audio and video compression.
When reading MP3 files, up to 28 bits of precision
is stored although only 16 bits is reported to user.
This is to allow the default behavior of writing 16 bit output files.
A user can specify a higher precision for the output file
to prevent lossing this extra information.
MP3 output files will use up to 24 bits of precision while encoding.
MP3 compression parameters can be selected using the
.Fl C
option as follows.
.Pp
The primary parameter to the LAME encoder is the bit rate.
If the argument to
.Fl C
is a positive integer, it is taken as the bitrate in kbps.
The second most important parameter is probably
.Dq quality
(means performance really), which allows balancing encoding speed vs quality.
In LAME, 0 specifies highest quality but is very slow,
while 9 selects poor quality, but is fast.
The value of 5 (no more, no less) is the default
and 2 is recommended as a good trade-off for high quality encoding.
The
.Fl C
argument is a float and the fractional part is used to select quality,
so 128.2 selects 128 kbps encoding with a quality of 2.
The problem is when specifying 128 kbps encoding with default quality,
0 means use default.
Instead of 0, use .01 to specify the highest quality.
LAME uses bitrate to specify a constant bitrate,
but higher quality can be achieved using Variable Bit Rate (VBR).
VBR quality (meaning size really) is selected using a number from 0 to 9.
Use a value of 0 for high quality, larger files,
and 9 for smaller files of lower quality.
The default is 4.
In order to squeeze the selection of VBR into the the
.Fl C
float argument we use negative numbers to select VRR.
For example, -4.2 selects the default
VBR encoding (size) with high quality (speed).
One special case is 0, which is a valid
VBR encoding parameter but not a valid bitrate.
Compression value of 0 is always treated as a high quality vbr,
and as a result both -0.2 and 0.2 are treated as
highest quality VBR (size) and high quality (speed).
.It m3u
A playlist format; contains a list of audio files.
SoX can read, but not write this file format.
.It nist
See sph.
.It ogg, vorbis (optional)
Ogg Vorbis compressed audio; an open, patent-free codec
designed for music and streaming audio.
It is a lossy compression format that achieves
good compression rates with a minimum amount of quality loss.
SoX can decode all types of Ogg Vorbis files,
and can encode at different compression levels/qualities
given as a number from -1 (highest compression/lowest quality)
to 10 (lowest compression, highest quality).
By default the encoding quality level is 3
(which gives an encoded rate of approx. 112 kbps);
this can be changed using the
.Fl C
option with a number from -1 to 10;
fractional numbers are also allowed.
.It opus (optional)
Xiph.org's Opus compressed audio; an open, lossy, low-latency codec
offering a wide range of compression rates, using the Ogg container.
SoX can only read Opus files, not write them.
.It oss (optional)
Open Sound System
.Pa /dev/dsp
device driver.
OSS support is used by
.Fx
FreeBSD and some other Unix operating systems.
.It paf, fap
Ensoniq PARIS file format (big and little-endian, respectively).
.It pls
A playlist format; contains a list of audio files.
SoX can read, but not write this file format.
.It prc
Psion Record.
Used in Psion EPOC PDAs (Series 5, Revo and similar) for
System alarms and recordings made by the built-in Record application.
When writing, SoX defaults to the recommended A-law encoding.
if you must use ADPCM, use the
.Fl e Dv ima-adpcm
switch.
.It pulseaudio (optional)
PulseAudio driver, a cross platform networked sound server.
.It pvf
Portable Voice Format.
.It sd2
Sound Designer 2 format.
.It sds (optional)
MIDI Sample Dump Standard.
.It sf
IRCAM SDIF (Institut de Recherche et Coordination Acoustique/Musique
Sound Description Interchange Format).
Used by music software such as the CSound package,
and the MixView sound sample editor.
.It sln
Asterisk PBX signed linear 8khz, 16-bit signed integer,
little-endian raw format.
.It sph, nist
SPHERE (SPeech HEader Resources) is a file format defined by NIST
(National Institute of Standards and Technology)
and is used with speech audio.
SoX can read these files when they contain \(*m-law and PCM data.
It will ignore any header information that says the data is
compressed using
.Xr shorten 1
compression and will treat the data as either \(*m-law or PCM.
Use
.Xr shorten 1
to decompress the data first.
.It smp
Turtle Beach SampleVision files.
SMP files are for use with the PC-DOS package
SampleVision by Turtle Beach Softworks.
This package is for communication to several MIDI samplers.
All sample rates are supported by the package,
although not all are supported by the samplers themselves.
Loop points are ignored.
.It snd
See
.Dq au ,
.Dq sndr
and
.Dq sndt .
.It sndfile (optional)
This is a pseudo-type that forces libsndfile to be used.
When writing, the file type is deduced from the output file name;
when reading, the type is deduced from the file content.
The supported formats are:
.\" FIXME this list begs to lag behind
raw,
aiff,
aiffc,
au,
caf,
flac,
htk,
mat4,
mat5,
ogg,
opus,
paf,
pvf,
sd2,
sds,
sf,
snd,
sph,
svx,
voc,
vorbis,
wav,
xi.
.It sndio (optional)
OpenBSD audio device driver.
.It sndr
Sounder files.
An MS-DOS/Windows format from the early '90s.
Sounder files usually have a
.Dq snd
extension.
.It sndt
SoundTool files.
An MS-DOS/Windows format from the early '90s.
SoundTool files usually have a
.Dq snd
extension.
.It sox
SoX's native uncompressed PCM format, intended for storing or piping
audio at intermediate processing points, i.e. between SoX invocations.
It has much in common with the popular uncompressed PCM formats,
but has the following specific characteristics:
the PCM samples are always stored as 32 bit signed integers,
the samples are stored by default in the native byte order,
and the number of samples in the file is recorded as a 64-bit integer.
Comments are also supported.
See
.Dq Special Filenames
in
.Xr sox 1
for examples of using the sox format with pipes.
.It sunaudio (optional)
Sun Microsystems
.Pa /dev/audio
device driver.
.It txw
Yamaha TX-16W sampler.
A file format from a Yamaha sampling keyboard
which wrote IBM-PC format 3.5" floppies.
SoX handles reading of files which do not have the sample rate field
set to one of the expected ones by looking at some other bytes
in the attack/loop length fields
and defaulting to 33 kHz if the sample rate is still unknown.
.It vms
See dvms.
.It voc
Sound Blaster VOC files.
VOC files are multi-part and contain silence parts, looping,
and different sample rates for different chunks.
On input, the silence parts are filled out, loops are rejected,
and sample data with a new sample rate is rejected.
Silence with a different sample rate is generated appropriately.
On output, silence is not detected, nor are impossible sample rates.
SoX supports reading (but not writing) VOC files with multiple blocks,
and files containing \(*m-law, A-law, and 2/3/4-bit ADPCM samples.
.It vorbis
See ogg.
.It vox
A headerless file of Dialogic/OKI ADPCM audio data
commonly comes with a
.Dq vox
extension.
This ADPCM data has 12-bit precision packed into only 4-bits.
Some early Dialogic hardware does not always
reset the ADPCM encoder at the start of each vox file.
This can result in clipping and/or DC offset problems
when decoding the audio.
Whilst little can be done about the clipping,
a DC offset can be removed by passing the decoded audio
through a high-pass filter, for example
.Sq sox input.vox output.wav highpass 10
.It w64
Sonic Foundry's 64-bit RIFF/WAV format.
.It wav
Microsoft WAV RIFF files.
This is the native audio file format of Windows,
and widely used for uncompressed audio.
SoX can read and write linear PCM, floating point,
\(*m-law, A-law, MS ADPCM, and IMA (or DVI) ADPCM encoded samples.
WAV files can also contain audio encoded in many other ways
(not supported with SoX) such as MP3;
in some cases such a file can still be read by SoX
by overriding the file type, as in
.Sq play -t mp3 mp3encoded.wav .
Big endian versions of RIFF files, called RIFX, are also supported:
to write a RIFX file, use the
.Fl B
option for the output file.
.It waveaudio (optional)
MS-Windows audio device driver.
.\"sox infile \-t waveaudio
.\"sox infile \-t waveaudio default
.\"sox infile \-t waveaudio 1
.\"sox infile \-t waveaudio "High Definition Audio Device ("
If the device name is omitted, or is -1 or
.Dq Bdefault ,
you get the `Microsoft Wave Mapper' device,
which means to use the system default audio devices.
You can control what that means via the Control Panel.
A device name given by any other number means
the audio device with that index;
so recording with device name 0 would get
the first input device (perhaps the microphone),
1 would get the second (perhaps line in), etc.
Playback using 0 will get the
first output device (usually the only audio device).
If the device name given is something other than a number,
SoX tries to match it (the first 31 characters)
.\" FIXME Is that enough? Those win names can be crazy
against the names of the available devices.
.It wavpcm
A non-standard, but widely used, variant of WAV.
.\" FIXME is that true?
Some applications cannot read a standard WAV file header
for PCM-encoded data with sample-size greater than 16-bits
or with more than two channels,
but can read a non-standard WAV header.
It is likely that such applications will eventually be updated
to support the standard header, but in the mean time,
this SoX format can be used to create files with
the non-standard header that should work with these applications.
.\" FIXME: throw that away
Note that SoX will automatically detect and read WAV files
with these non-standard headers.
The most common use of this file-type
is likely to be something like
.Pp
.Dl sox infile.any -t wavpcm -e signed-integer outfile.wav
.It wv (optional)
WavPack lossless audio compression.
When converting WAV to this format and back again,
the RIFF header is not necessarily preserved losslessly,
even though the audio data is.
.It wve
Psion 8-bit A-law, used on Psion SIBO PDAs (Series 3 and similar).
.It xa
Maxis XA files.
These are 16-bit ADPCM audio files used by Maxis games.
SoX onluy supports reading XA files.
.It xi
Fasttracker 2 Extended Instrument format.
.El
.Sh SEE ALSO
.Xr sox 1 ,
.Xr soxi 1
.Sh AUTHORS
.An Chris Bagwell Aq Mt cbagwell@users.sourceforge.net
.\"Copyright 1991 Lance Norskog and Sundry Contributors.
.\"Copyright 1998-2013 Chris Bagwell and SoX Contributors.
