.Dd June 8, 2024
.Dt SOXI 1
.Os
.Sh NAME
.Nm soxi
.Nd display audio file metadata
.Sh SYNOPSIS
.Nm
.Op Fl V Ar level
.Op Fl T
.Op Fl aBbcDdeprst
.Ar
.Sh DESCRIPTION
.Nm
displays information from the headers of given audio files.
Supported audio file types are listed and described in
.Xr soxformat 7 .
Note that some of them are raw formats with no header.
.Pp
By default, all available information is shown.
The following options can be used to select individual pieces.
.Pp
.Bl -tag -compact -width V_num_
.It Fl V Op Ar n
Set verbosity.
See
.Xr sox 1
for details.
.It Fl T
Changes the behaviour of
.Fl D ,
.Fl d
and
.Fl s
to display the total across all given files.
Note that the total of
.Fl s
with files using different sampling rates is of questionable value.
.It Fl a
Show file comments (annotations) if available.
.It Fl B
Show the bitrate averaged over the whole file (0 if unavailable).
.It Fl b
Show number of bits per sample (0 if not applicable).
.It Fl c
Show number of channels.
.It Fl D
Show duration in seconds (0 if unavailable).
.It Fl d
Show duration in hours, minutes and seconds (0 if unavailable).
.It Fl e
Show the name of the audio encoding.
.It Fl p
Show estimated sample precision in bits.
.It Fl r
Show sample-rate.
.It Fl s
Show number of samples (0 if unavailable).
.It Fl t
Show detected file-type.
.El
.Sh SEE ALSO
.Xr sox 1 ,
.Xr libsox 3 ,
.Xr soxformat 7
.Sh AUTHORS
.An Chris Bagwell Aq Mt cbagwell@users.sourceforge.net
.\"Copyright 2008\-2013 by Chris Bagwell and SoX Contributors.
.\"
.\"This program is free software; you can redistribute it and/or modify
.\"it under the terms of the GNU General Public License as published by
.\"the Free Software Foundation; either version 2, or (at your option)
.\"any later version.
.\"
.\"This program is distributed in the hope that it will be useful,
.\"but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"GNU General Public License for more details.
