.Dd March 19, 2018
.Dt SOXI 1
.Os
.Sh NAME
.Nm soxi
.Nd display sound file metadata
.Sh SYNOPSIS
.Nm
.Op Fl abBcdDeprstT
.Op Fl V Ar level
.Ar
.Sh DESCRIPTION
.Nm
displays information from the header of a given audio file or files.
Supported audio file types are described in
.Xr soxformat 7 .
.Pp
By default,
.Nm
displays all information available in the file header.
A subset can be selected with options as follows:
.Pp
.Bl -tag -width levelXXX -compact
.It Fl a
Show file comments (annotations).
.It Fl b
Show number of bits per sample (0 if not applicable).
.It Fl B
Show the averaged bitrate (0 if unavailable).
.It Fl c
Show number of channels.
.It Fl d
Show duration in hours, minutes and seconds (0 if unavailable).
.It Fl D
Show duration in seconds (0 if unavailable).
.It Fl e
Show the name of the audio encoding.
.It Fl p
Show estimated sample precision in bits.
.It Fl r
Show sample-rate.
.It Fl s
Show number of samples (0 if unavailable).
.It Fl t
Show detected file-type.
.It Fl T
Display totals across given files for
.Fl D ,
.Fl d ,
and
.Fl s .
.\"Note that
.\".Fl Ts
.\"is of questionable value with
.\"files of different sampling rates.
.It Fl V Ar level
Set verbosity.
See
.Xr sox 1
for details.
.El
.Sh SEE ALSO
.Xr sox 1 ,
.Xr libsox 3 ,
.Xr soxformat 7
.Sh AUTHORS
.An Chris Bagwell Aq Mt cbagwell@users.sourceforge.net
