#!/bin/sh

# FIXME This should be probabaly consolidated into test-format-conversion
effect="$@"

t() {
	format=$1
	shift
	opts="$*"

	#echo "Format: $format   Options: $opts"
	echo sox file.wav $opts /tmp/file.$format $effect
	#sox $opts /tmp/file.$format /tmp/file1.wav  $effect
}
t 8svx
t aiff
t aifc
t au 
t avr -e unsigned-integer
t cdr
t cvs
t dat
t hcom -r 22050
t maud
t prc
t prc -e signed-integer
t sf 
t smp
t sndt 
t txw
t ub -r 8130
t vms
t voc
t vox -r 8130
t wav
t wve
